### ISSUE TITLE
Strange error during compile

### ISSUE THREAD

**Issue by cstamas** [groovy/groovy-eclipse#1363]
Use following:
* Java 17 Temurin
* maven 3.8.5
* groovy 4.0.2
* maven-compiler-plugin 3.10.1
* groovy-eclipse-compiler 3.7.1
* groovy-eclipse-batch 4.0.2-02

When am building project I get this strange error:

```
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ px-reports-plugin ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] /*
	^
Groovy:Access to ConfigT#repositoryId is forbidden
[INFO] 1 problem (1 error)
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Found 1 error and 0 warnings.
[INFO] 1 error
```

Tried to create a reproducer but it does NOT reproduce the issue (but at least helps me to describe how my project looks like):
https://github.com/cstamas/groovy-eclipse-bug/

Strange issues:
* compilation error does not tell class name nor line number (luckily this module has ONE groovy class, so it was easy to find it).
* situation is pretty much like in reproducer: a generic support class and groovy class with inner class.
* groovy compiler claims that inner class field access is forbidden, but mentions superclass generic name....
* the use of `@CompileStatic` is intentional

Also, any other tips what to look for?

**Comment by eric-milles** [comment]
What does `ConfigT#repositoryId` map to in your sample project?  Is that what you have represented as `data.prop` where `data` is parameterized property from superclass and `prop` should refer to the property of local inner class?

**Comment by cstamas** [comment]
That's right, you got it all right

**Comment by eric-milles** [comment]
Is there a lot more in your groovy source or in the support classes?  It is hard to proceed without recreation.

**Comment by cstamas** [comment]
I know, tomorrow will try to make reproducer reproduce, today could not make it. This is job related, so sadly cannot hand over the source that produces this error, am hoping reproducer will do it.

**Comment by cstamas** [comment]
Btw, this code was ok with groovy 3.0.10, when upgraded groovy (and compiler) to 4.0.2, this error happens on unmodified source.

**Comment by eric-milles** [comment]
So `data` is visited as `this.data` if there is no accessible declared field or static outer field named "data".  That can be seen here: https://github.com/apache/groovy/blob/GROOVY_4_0_X/src/main/java/org/codehaus/groovy/classgen/AsmClassGenerator.java#L1179

[GROOVY-8448](https://issues.apache.org/jira/browse/GROOVY-8448), GROOVY-9501, GROOVY-9569, GROOVY-9650, GROOVY-9655, GROOVY-9665, GROOVY-9683, GROOVY-9695 are some fixes made in this code.

From there, it writes a direct method call to `Inner#getProp()` because it located a `PropertyNode` for "prop".  https://github.com/apache/groovy/blob/GROOVY_4_0_X/src/main/java/org/codehaus/groovy/classgen/asm/InvocationWriter.java#L175

So I think the detection of field or property might be getting thrown off somewhere.

**Comment by eric-milles** [comment]
If an access method cannot be found, classgen falls through to `makeGetField` and if field is not accessible, it will fall to the end where the forbidden error is emitted: https://github.com/apache/groovy/blob/GROOVY_4_0_X/src/main/java/org/codehaus/groovy/classgen/asm/sc/StaticTypesCallSiteWriter.java#L189

**Comment by eric-milles** [comment]
If "prop" is a private field, it runs through `makeGetPrivateFieldWithBridgeMethod` which could fail to generate a bridge method call if private bridge checks failed earlier in STC.

**Comment by eric-milles** [comment]
In your original source, is "data.prop" part of a method call, assignment or some other construct?

**Comment by adreghiciu** [comment]
is used in 2 ways in different places:
* as parameter to a method call
* as a retun value in a closure

**Comment by eric-milles** [comment]
Probably gets different treatment when part of a closure.

**Comment by eric-milles** [comment]
https://issues.apache.org/jira/browse/GROOVY-10637
