### ISSUE TITLE
Unable to open Java sources after updating 2021-09 to 2021-12

### ISSUE THREAD

**Issue by digulla** [groovy/groovy-eclipse#1319]
I've just updated 2021-09 to 2021-12 using Oomph.

After the update, I can't open the Java editor anymore:

````
java.lang.NoClassDefFoundError: org/codehaus/groovy/eclipse/editor/GroovyAwareFoldingStructureProvider
	at org.codehaus.groovy.eclipse.GroovyPlugin$1.getCurrentFoldingProvider(GroovyPlugin.java:182)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor.createSourceViewer(JavaEditor.java:1891)
	at org.eclipse.ui.texteditor.AbstractTextEditor.createPartControl(AbstractTextEditor.java:3369)
````

There are two problems here:

1. I'm not aware I had the Groovy Plugin installed before. I have a second Eclipse with Groovy because the Groovy Plugin breaks 90% of p2 updates.
2. I can't uninstall the Groovy Plugin; it's not listed in the dialog where I can uninstall features. It's only in the features tab and the plugins tab.

How do I get rid of Groovy?

How can I make sure that Groovy is never, ever installed without my consent?

As far as I can see, the plugin is complete. Why do I get NoClassDefFoundError???

**Comment by digulla** [comment]
Details from the about dialog:

Eclipse Groovy Development Tools

Version: 4.1.0.v202103311613-e2103-RELEASE

Copyright (c) 2009-2021 Pivotal Software, Inc. and others. All rights reserved.
Visit https://github.com/groovy/groovy-eclipse/wiki

Features:

Pivotal Software, Inc.	Groovy-Eclipse	4.1.0.v202103311613-e2103-RELEASE	org.codehaus.groovy25.feature
Pivotal Software, Inc.	Groovy-Eclipse	4.1.0.v202103311613-e2103-RELEASE	org.codehaus.groovy.eclipse.feature

Plug-ins:

	Pivotal Software, Inc.	Apache Groovy	2.5.14.v202103311613-e2103-RELEASE	org.codehaus.groovy
	Pivotal Software, Inc.	Groovy Ant support	4.1.0.v202103311613-e2103-RELEASE	org.codehaus.groovy.eclipse.ant
	Pivotal Software, Inc.	Groovy AST Views	4.1.0.v202103311613-e2103-RELEASE	org.codehaus.groovy.eclipse.astviews
	Pivotal Software, Inc.	Groovy Code Assist	4.1.0.v202103311613-e2103-RELEASE	org.codehaus.groovy.eclipse.codeassist
	Pivotal Software, Inc.	Groovy Code Browsing	4.1.0.v202103311613-e2103-RELEASE	org.codehaus.groovy.eclipse.codebrowsing
	Pivotal Software, Inc.	Groovy Compiler Resolver	4.1.0.v202103311613-e2103-RELEASE	org.codehaus.groovy.eclipse.compilerResolver
	Pivotal Software, Inc.	Groovy Core	4.1.0.v202103311613-e2103-RELEASE	org.codehaus.groovy.eclipse.core
	Pivotal Software, Inc.	Groovy DSL support	4.1.0.v202103311613-e2103-RELEASE	org.codehaus.groovy.eclipse.dsl
	Pivotal Software, Inc.	Groovy-Eclipse	4.1.0.v202103311613-e2103-RELEASE	org.codehaus.groovy.eclipse
	Pivotal Software, Inc.	Groovy-Eclipse integration	4.1.0.v202103311613-e2103-RELEASE	org.eclipse.jdt.groovy.core
	Pivotal Software, Inc.	Groovy Quick Fix	4.1.0.v202103311613-e2103-RELEASE	org.codehaus.groovy.eclipse.quickfix
	Pivotal Software, Inc.	Groovy Refactoring	4.1.0.v202103311613-e2103-RELEASE	org.codehaus.groovy.eclipse.refactoring
	Pivotal Software, Inc.	Groovy UI	4.1.0.v202103311613-e2103-RELEASE	org.codehaus.groovy.eclipse.ui

**Comment by digulla** [comment]
I agree this is probably a bug somewhere in p2 / Oomph. I created it here because people are going to search for the error message and "Groovy".

**Comment by rolfth** [comment]
If the Groovy patch depends on specific JDT version, this should be managed on the Groovy side by specifying the expected version ranges of the JDT plugins in the manifest. When ranges are correctly specified, p2 and oomph will correctly handle this case to prevent conflicts in the installation.

**Comment by eric-milles** [comment]
So what am I missing: https://github.com/groovy/groovy-eclipse/blob/master/jdt-patch/e422/Feature-org.codehaus.groovy.jdt.patch/feature.xml#L21

**Comment by rolfth** [comment]
Okey, not my full expertise, but it seems that https://github.com/groovy/groovy-eclipse/blob/master/ide/org.codehaus.groovy.eclipse.ui/src/org/codehaus/groovy/eclipse/GroovyPlugin.java gets installed even when the feature patch is no longer installed. So after an update the feature patch is no longer applied as the JDT feature is upgraded.

Somehow it must be ensured in https://github.com/groovy/groovy-eclipse/blob/master/ide/org.codehaus.groovy.eclipse.ui/META-INF/MANIFEST.MF that the groovy patch is present when this plugin is installed. Maybe by depending on the patched version of the jdt or by the enclosed feature, though I don't know if this leads to unexpected side effects and how robust this is.

**Comment by JacquesLeRoux** [comment]
Thanks @eric-milles, very useful!

**Comment by eric-milles** [comment]
Eclipse 4.22:
`public Map<String, List<IAdapterFactory>> getFactories() {`

Eclipse 4.21:
`public HashMap<String, List<IAdapterFactory>> getFactories() {`

It seems you have a misalignment between Eclipse IDE and Groovy Development Tools.

**Comment by JacquesLeRoux** [comment]
Hi @eric-milles,

I use Eclipse 4.22, so I followed your advice:
> When you use auto-update to cross major versions of eclipse, the Groovy Development Tools JDT patch gets out of sync. You need a newer update site link for Eclipse 2021-12: https://dist.springsource.org/snapshot/GRECLIPSE/e4.22
and got this error. Then I uninstalled Groovy, got back to what Marketplace suggests (ie Version: 4.4.0.v202112311714-e2112-RELEASE) and still got the same error. 

In our project (Apache OFBiz) we still use Groovy 2.5.11, so I tried to install GDT 3.5.0. Eclipse refused and suggested something else. It worked. I have now a mix of installed versions (3 4.50 and 1 4.40) but at least it works :)
