### ISSUE TITLE
On Groovy 3.x AbstractMethodError for getProperty()

### ISSUE THREAD

**Issue by mpiggott** [groovy/groovy-eclipse#1499]
I'm not sure whether this question is specific to the groovy-eclipse-compiler or whether its more appropriate for the Groovy core lists.

I've been updating from Groovy 2.4 to 3.0, however I'm running into runtime errors of the form:

```
Caused by: java.lang.AbstractMethodError: {MyClassWrittenInGroovy}.getProperty(Ljava/lang/String;)Ljava/lang/Object;
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:310)
```

I've tried both 3.0.8 and 3.0.18 of Groovy (3.0.8 as its the last version groovy-eclipse-batch available via central, though I've tried manual downloads of 3.0.18-02 too)

While searching there don't appear to be many others running into this, but the posts I did find suggest of mixed Groovy versions though I haven't been able to find any evidence of this.

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <dependencies>
    <!--
    Keep versions in sync with buildsupport/groovy/pom.xml
    -->
    <dependency>
        <groupId>org.codehaus.groovy</groupId>
        <artifactId>groovy-eclipse-compiler</artifactId>
        <version>3.7.0</version>
    </dependency>
    <dependency>
        <groupId>org.codehaus.groovy</groupId>
        <artifactId>groovy-eclipse-batch</artifactId>
        <version>3.0.8-01</version>
    </dependency>
  </dependencies>
</plugin>
```

I consulted with `groovy-all` and pruned test/dev/console jars:

```
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy</artifactId>
    <version>${groovy.version}</version>
</dependency>
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-ant</artifactId>
    <version>${groovy.version}</version>
</dependency>
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-astbuilder</artifactId>
    <version>${groovy.version}</version>
</dependency>
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-datetime</artifactId>
    <version>${groovy.version}</version>
</dependency>
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-jmx</artifactId>
    <version>${groovy.version}</version>
</dependency>
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-json</artifactId>
    <version>${groovy.version}</version>
</dependency>
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-jsr223</artifactId>
    <version>${groovy.version}</version>
</dependency>
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-macro</artifactId>
    <version>${groovy.version}</version>
</dependency>
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-nio</artifactId>
    <version>${groovy.version}</version>
</dependency>
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-sql</artifactId>
    <version>${groovy.version}</version>
</dependency>
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-templates</artifactId>
    <version>${groovy.version}</version>
</dependency>
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-xml</artifactId>
    <version>${groovy.version}</version>
</dependency>
```

**Comment by mpiggott** [comment]
Including this in the off-chance it raises a redflag, if I update gmavenplus 1.5 to the last 1.x or 3.x I also see a missing method error in Groovy

```
Caused by: java.lang.NoSuchMethodError: org.codehaus.groovy.runtime.memoize.EvictableCache.getAndPut(Ljava/lang/Object;Lorg/codehaus/groovy/runtime/memoize/MemoizeCache$ValueProvider;)Ljava/lang/Object;
    at org.codehaus.groovy.transform.stc.AbstractExtensionMethodCache.get (AbstractExtensionMethodCache.java:51)
```

**Comment by eric-milles** [comment]
Not sure what runtime version you are using.  But when you compile with Groovy 3+, the GroovyObject methods are no longer compiled into your class, but are instead deafult methods on the interface.  If you have any libraries compiled against Groovy 2.x, you sould add this to your groovy class.  But it is probably better to ensure you are compiled against Groovy 3 across the board.

{code:groovy}
class Pogo {
  ...
  Object getProperty(String name) {
    super.getProperty(name) // delegate to GroovyObject#getProperty
  }
}
{code}

Another approach would be to compile with Groovy 2.4 or 2.5 until your runtime is Groovy 3 all the way.

**Comment by mpiggott** [comment]
I'm using Groovy 3.0.18 (and have also tried 3.0.8).

Assuming the compiler config snippet above is correct we're running it all with the same version as it was compiled with. 

On our CI system I've also gone through the build logs and didn't find any downloading of Groovy aside from the expected 3.0.18.

**Comment by eric-milles** [comment]
I see that you are compiling with 3.0.8 or 3.0.18 of `groovy-eclipse-batch`.  But I don't know what `groovy.version` is set to for your build or what groovy libraries are part of your runtime environment.  As I noted, Groovy 3+ adds default methods to `GroovyObject` and does not compile them into each class.  This is likely why you are seeing an abstract method error for `getProperty(String)`.

**Comment by mpiggott** [comment]
>  But I don't know what groovy.version is set to for your build or what groovy libraries are part of your runtime environment

As mentioned previously the version of Groovy used for compilation, and at runtime is the same version as is specified for `groovy-eclipse-batch`
